services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: verxio
      POSTGRES_PASSWORD: verxio
      POSTGRES_DB: verxio
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  validator:
    image: ghcr.io/samui-build/samui-test-validator:latest
    ports:
      - '8899:8899'
      - '8900:8900'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_HELIUS_API_KEY=${NEXT_PUBLIC_HELIUS_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - PINATA_JWT=${PINATA_JWT}
      - PRISMA_FIELD_ENCRYPTION_KEY=${PRISMA_FIELD_ENCRYPTION_KEY}
      - NEXT_PUBLIC_GATEWAY_URL=${NEXT_PUBLIC_GATEWAY_URL}
      - NEXT_PUBLIC_HELIUS_API_KEY={NEXT_PUBLIC_HELIUS_API_KEY}

networks:
  verxio-network:
    driver: bridge

volumes:
  postgres_data:
