name: Release Protocol SDK

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on version tags like v0.1.2

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./protocol
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - run: pnpm install
        working-directory: ${{ github.workspace }}

      - name: Build protocol package
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
